version: '3'
services:
  setup:
    image: ubuntu18-torch:suqerquadric_parsing
    volumes:
        - $PWD:/workspace
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - http_proxy=$http_proxy
          - https_proxy=$https_proxy
    command: pip install --user -e . 
